/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/archetype` | `/archetype`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/diagnostic-result` | `/diagnostic-result`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/diagnostic` | `/diagnostic`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/subscription` | `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/help` | `/help`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/journey` | `/journey`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/legal` | `/legal`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/archetype` | `/archetype`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/diagnostic-result` | `/diagnostic-result`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/diagnostic` | `/diagnostic`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/subscription` | `/subscription`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/help` | `/help`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/journey` | `/journey`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/legal` | `/legal`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/archetype${`?${string}` | `#${string}` | ''}` | `/archetype${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/diagnostic-result${`?${string}` | `#${string}` | ''}` | `/diagnostic-result${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/diagnostic${`?${string}` | `#${string}` | ''}` | `/diagnostic${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/subscription${`?${string}` | `#${string}` | ''}` | `/subscription${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/help${`?${string}` | `#${string}` | ''}` | `/help${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/journey${`?${string}` | `#${string}` | ''}` | `/journey${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verify${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/legal${`?${string}` | `#${string}` | ''}` | `/legal${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/archetype` | `/archetype`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/diagnostic-result` | `/diagnostic-result`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/diagnostic` | `/diagnostic`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/subscription` | `/subscription`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/help` | `/help`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/journey` | `/journey`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/legal` | `/legal`; params?: Router.UnknownInputParams; };
    }
  }
}
